# Generated by Django 3.0 on 2019-12-17 11:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogg', '0003_auto_20191217_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='catalogg.Genre'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('962abaab-703c-4bb7-a5a9-2d5eb3c6c4d3'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
