# Generated by Django 3.0 on 2019-12-17 11:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogg', '0004_auto_20191217_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['date_due_back']},
        ),
        migrations.RenameField(
            model_name='bookinstance',
            old_name='due_back',
            new_name='date_due_back',
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d980dc70-91c3-4e16-80ba-252c0264ceed'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
