# Generated by Django 3.0 on 2019-12-18 21:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogg', '0005_auto_20191217_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='catalogg.Book'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('252030b3-e0da-4830-85aa-139e33ea52d1'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
